import type { EnvVarDefinition } from "../types.js";

export const TEST_ENV_VARS = [
  {
    name: "E2E_BASE_URL",
    group: "test",
    type: "url",
    status: "active",
    defaultValue: "http://localhost:3001",
    description: "Playwright base URL override.",
  },
  {
    name: "E2E_MODEL_SLOT",
    group: "test",
    type: "string",
    status: "active",
    defaultValue: "e2e",
    description: "Model slot used by the e2e plugin verification script.",
  },
  {
    name: "CI",
    group: "test",
    type: "boolean",
    status: "active",
    defaultValue: "false",
    description: "CI mode for lint and Playwright behavior.",
  },
  {
    name: "LIVE_LLM_ENABLED",
    group: "test",
    type: "boolean",
    status: "active",
    defaultValue: "false",
    description: "Enables live LLM provider tests.",
  },
  {
    name: "LIVE_IMAGE_ENABLED",
    group: "test",
    type: "boolean",
    status: "active",
    defaultValue: "false",
    description: "Enables live image-generation provider tests.",
  },
  {
    name: "BASE_URL",
    group: "test",
    type: "url",
    status: "active",
    defaultValue: "http://localhost:5173",
    description: "README screenshot script frontend URL.",
  },
  {
    name: "SESSION_ID",
    group: "test",
    type: "string",
    status: "active",
    description: "README screenshot script session id.",
  },
  {
    name: "COVEL_PG_PREFLIGHT_HOST",
    group: "test",
    type: "string",
    status: "active",
    defaultValue: "127.0.0.1",
    description: "dev:pg TCP preflight target host.",
  },
  {
    name: "COVEL_PG_PREFLIGHT_PORT",
    group: "test",
    type: "integer",
    status: "active",
    defaultValue: "5432",
    description: "dev:pg TCP preflight target port.",
  },
  {
    name: "COVEL_PG_PREFLIGHT_SKIP",
    group: "test",
    type: "boolean",
    status: "documented",
    defaultValue: "false",
    description: "Documented dev:pg preflight bypass flag.",
  },
  {
    name: "COVEL_STORY_BASE_URL",
    group: "test",
    type: "url",
    status: "documented",
    description: "Documented story LLM endpoint override for e2e tests.",
  },
  {
    name: "COVEL_PLUGIN_BASE_URL",
    group: "test",
    type: "url",
    status: "documented",
    description: "Documented plugin LLM endpoint override for e2e tests.",
  },
] as const satisfies readonly EnvVarDefinition[];
