import type { PluginRegistrar } from "@covel/plugin-runtime";
import type {
  RuntimeHandlerContext,
  RuntimeHandlerResult,
} from "@covel/plugin-runtime";
import {
  buildTransitionPrompt,
  buildFallbackTransition,
  buildCharacterCreationBlock,
} from "./logic.js";

export default function register(registrar: PluginRegistrar) {
  registrar.addRuntimeHandler("init-wizard", initWizardHandler);
}

/**
 * On session_start, emit:
 * 1. A short narrative transition (generated by LLM reading the opening narrative)
 * 2. A character_creation UI block with only a name field
 */
async function initWizardHandler(
  ctx: RuntimeHandlerContext
): Promise<RuntimeHandlerResult> {
  // Extract the narrator's opening narrative from the runtime context
  const view = ctx.context as Record<string, unknown>;
  const previousOutputs = view.previousOutputs as
    | Array<{ narrative?: string }>
    | undefined;
  const openingNarrative =
    previousOutputs
      ?.map((o) => o.narrative)
      .filter(Boolean)
      .join("\n") ?? "";

  // Generate a contextual transition via LLM
  let transitionText = "";
  if (ctx.generateText && openingNarrative) {
    try {
      const prompt = buildTransitionPrompt(openingNarrative, ctx.locale);
      const result = await ctx.generateText(prompt);
      if (result?.trim()) {
        transitionText = result.trim();
      }
    } catch (err: unknown) {
      console.warn('[core-init-wizard] Transition generation failed:', err instanceof Error ? err.message : err);
    }
  }

  // Static fallback
  if (!transitionText) {
    transitionText = buildFallbackTransition(ctx.locale);
  }

  const proposals: Array<{ kind: string; payload: unknown }> = [];

  // 1. Narrative transition
  proposals.push({
    kind: "narrative.append",
    payload: { text: transitionText },
  });

  // 2. Character creation block (name only, minimal)
  proposals.push(buildCharacterCreationBlock(ctx.locale));

  return { proposals };
}
