import { describe, expect, it } from "vitest";
import { findLoreQualityErrors } from "./validation-helpers.js";

function loreWith(content: string): string {
  return `# The Glass City

${content}

1. Repair the broken gate.
2. Find the missing keeper.
3. Stop the coming storm.`;
}

describe("findLoreQualityErrors", () => {
  it.each([
    ["framework", "A technomantic framework binds every tower together."],
    ["model", "The senate follows a social model inherited from its founders."],
    ["cost", "Every ritual carries a terrible cost."],
    ["api", "The oracle Api records each oath."],
    ["test", "The pilgrimage ends with a test of courage."],
    ["prompt", "The sentry took prompt action when the beacon failed."],
    ["cheap", "The dockside tavern serves cheap wine."],
    [
      "software framework",
      "The archive runs on an ancient software framework.",
    ],
    [
      "REST API",
      "The machine-city exposes its laws through a REST API endpoint.",
    ],
    ["Chinese model", "工匠依照城市模型重建了倒塌的钟楼。"],
  ])("allows %s when it belongs to the setting", (_name, content) => {
    expect(findLoreQualityErrors(loreWith(content))).toEqual([]);
  });

  it.each([
    "This world is a test fixture for validation.",
    "This lore is model output generated by an LLM.",
    "The prompt instructions require a generic fantasy setting.",
    "This package uses a cheap LLM generation pipeline.",
    "这是一个低成本快速验证用的世界。",
    "这段世界设定来自模型输出。",
  ])("rejects explicit generation meta wording: %s", (content) => {
    expect(findLoreQualityErrors(loreWith(content))).toContain(
      "WORLD.md contains explicit generation meta wording",
    );
  });
});
